[package]
name = "rustro_arch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.0"
winit = "0.26.0"
font-kit = "0.7.0"