name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: macOS-latest
          - os: ubuntu-latest
    steps:
    - name: Installing macOS dependencies
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config portaudio
    - name: Installing needed Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev
    - uses: actions/checkout@v3
    - name: Build for ${{ matrix.os }}
      run: cargo build --release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-artifacts
        path: target/release/rustro_arch
env:
  CARGO_TERM_COLOR: always
