name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: macOS-latest
            features: portaudio_backend,rodio_backend,dbus_keyring
          - os: ubuntu-latest
            features: alsa_backend,rodio_backend,dbus_keyring,dbus_mpris
    steps:
    - uses: actions/checkout@v3
    - name: Build for ${{ matrix.os }}
      run: cargo build --release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-artifacts
        path: target/release/rustro_arch
env:
  CARGO_TERM_COLOR: always
